export const appZh: Record<string,string> = {
  'CAG experiment':'CAG 交互实验',
  'An explorable explanation':'交互式论文解释',
  'About this model':'关于模型',
  'When prediction gets the decision wrong.':'预测准确，决策仍可出错。',
  'Outcome levels drift.':'结果水平随时间漂移。',
  'Action geometry may persist.':'动作几何可能持续。',
  'Interactive CAG teaching experiment':'CAG 交互式教学实验',
  'Experiment steps':'实验步骤',
  'Observe periods':'观察各期',
  'Pool across time':'跨时间混合',
  'Keep the shape':'保留形状',
  'Choose before the future':'先决策，再揭示',
  'Change the future':'改变未来形状',
  'The previous future branch was discarded because the history changed. Choose again to freeze the new history.':'历史配置已改变，旧未来分支已失效。请重新选择，冻结新的历史规则。',
  'Action × period × response':'动作 × 时期 × 响应',
  'Pause rotation':'暂停旋转',
  'Resume rotation':'恢复旋转',
  'Reset view':'重置视角',
  'Front view':'正面视角',
  'Exit fullscreen':'退出全屏',
  'Fullscreen scene':'全屏查看',
  'Exit':'退出',
  'The selected scale has no valid action geometry.':'所选尺度下没有有效的动作几何。',
  'Loading the 3D experiment…':'正在加载 3D 实验…',
  '3D is unavailable. The 2D experiment remains fully interactive.':'3D 不可用，2D 实验仍可完整交互。',
  'Use the controls and synchronized plots below.':'请使用参数控件和同步图表。',
  'Show samples':'显示样本',
  'Same action, all periods':'同一动作，跨期比较',
  'Period':'时期',
  'Early':'早期',
  'Middle':'中期',
  'Late':'后期',
  'Disable 3D interaction':'退出 3D 操作',
  'Enable 3D interaction':'开启 3D 操作',
  'Time depth collapsed for shape comparison':'时间深度已折叠，便于比较形状',
  'Seven known response curves; samples hidden':'七条已知响应曲线，样本点已隐藏',
  'Revealed truth divided by its positively profiled amplitude':'揭示的真值除以其剖面拟合的正幅度',
  'Scaled comparison unavailable; raw truth remains below':'无法作正尺度比较，下方仍显示原始真值',
  'Future diagnostic unavailable':'未来诊断不可用',
  'Dashed future: dimensionless assumed continuation':'未来虚线：无量纲的假定延续',
  'Known responses at action':'该动作处的已知响应',
  'Illustrative geometry fit on known response curves':'基于已知响应曲线的几何拟合示意',
  '. No full CAG estimator is trained on these points.':'。这些点未用于训练完整 CAG 估计器。',
  'Known synthetic response curves. Illustrative geometry; no CAG estimator is trained on these points.':'已知的合成响应曲线与几何示意；这些点未用于训练 CAG 估计器。',
  'No valid action geometry on this response scale.':'此响应尺度下没有有效的动作几何。',
  'Ideal pooled predictor':'理想的时间混合预测器',
  'Population E[Y | A = a], not a poor fit.':'总体 E[Y | A = a]，偏差并非源于拟合不良。',
  'Teaching model notes':'教学模型说明',
  'A teaching model, with a defined scope':'教学模型的适用范围',
  'This fixed-history example isolates time mixing. The additive default fixes amplitude drift at zero; log presets introduce positive amplitude drift or a historical scale tie.':'本例固定历史配置，只展示时间混合。默认加性模型的幅度漂移为零；对数预设引入正幅度变化，或展示历史尺度并列拟合。',
  "It is not a paper experiment, a causal identification demonstration from confounded logs, or the full CAG estimator. The paper's synthetic, RDSS and Taobao results are separate. All responses, sample points and revealed future diagnostics here are simulated.":'这里不是论文实验，也不是从混杂日志识别因果效应或实现完整 CAG 估计器。论文的 synthetic、RDSS 与 Taobao 结果单独报告。这里的响应、样本和揭示后的未来诊断均为合成教学数据。',
  'A historical tie need not identify the scale that persists into future calibration. Geometry loss and deployment regret are different quantities.':'历史拟合并列不能唯一识别未来仍会持续的尺度。几何损失与部署遗憾值是不同的量。',
  'Causal action geometry':'因果动作几何',
  'Teaching model · P3 review':'教学模型 · P3 审阅版',
  'Skip to experiment':'跳转到实验',
  'Language':'语言',
  'Copy link':'复制链接',
  'Close share link':'关闭分享链接',
  'Close':'关闭',
  'Link copied.':'链接已复制。',
  'Copy the link below.':'请手动复制下方链接。',
  'Shareable experiment link':'可分享的实验链接',
  'Shared futures start hidden and require Reveal again.':'分享链接中的未来默认隐藏，需再次点击揭示。',
  'Shared inputs restored. Future truth stays hidden until Reveal.':'已恢复分享参数；未来真值在点击揭示前保持隐藏。',
  'The shared link is invalid or uses an unsupported version. Showing the default experiment.':'分享链接无效或版本不受支持，已显示默认实验。',
  'Previewing hovered period':'正在预览悬停的时期',
  'Action cursor':'动作游标',
  'Action':'动作',
  'The cursor changes the view, not the frozen decision.':'游标只改变观察位置，不改变冻结的决策。',
  'Paper & evidence':'论文与证据',
  'NeurIPS 2026 · Sydney poster':'NeurIPS 2026 · Sydney 海报',
  'Official NeurIPS page':'NeurIPS 官方页面',
  'The paper develops a two-stage orthogonal estimator and reports synthetic and e-commerce pricing experiments. The interactive numbers above come from a separate known-response teaching model.':'论文提出两阶段正交估计器，并报告 synthetic 与电商定价实验。上方交互中的数值来自单独设计的已知响应教学模型。',
  'The official page is the source for paper information. Numerical paper results are not reproduced in this explorable.':'论文信息以官方页面为来源。本交互页不复现论文的数值实验结果。',
  'Shared experiment inputs':'分享的实验参数',
  'No identified history geometry to freeze.':'没有已识别的历史几何可供冻结。',
};
