export const componentsZh: Record<string, string> = {
  'Change the history': '调整历史数据',
  'Reset experiment': '重置实验',
  'Baseline drift': '基线漂移',
  'How much response levels change over time': '响应水平随时间变化的程度',
  'Logging drift': '记录策略漂移',
  'How much logged actions move from low to high': '记录的动作从小到大移动的程度',
  'Log': '对数',
  'Additive': '加性',
  'teaching preset · amplitude drift': '教学预设 · 幅度漂移',
  'Work with known response curves': '处理已知响应曲线',
  'Teaching preset': '教学预设',
  'Additive drift': '加性漂移',
  'Log scale with amplitude drift': '对数尺度与幅度漂移',
  'Pure multiplicative drift': '纯乘性漂移',
  'View a response scale': '选择响应尺度视图',
  'Identity scale': '恒等尺度',
  'Log scale': '对数尺度',
  'Remove the calibration': '移除校准差异',
  'Linked response': '尺度变换后的响应',
  'Anchor contrasts': '参考动作对比',
  'Remove amplitude': '移除幅度',
  'Historical geometry loss': '历史几何损失',
  'Scale': '尺度',
  'Profiled loss': '剖面损失',
  'Identity': '恒等',
  'Selection': '选择结果',
  'Both scales fit': '两种尺度均拟合',
  'No action signal': '无动作信号',
  'Invalid scale': '无效尺度',
  'Selected geometry action': '所选几何形状的动作',
  'Gap < 10⁻⁸. Identity is the deterministic tie preference; the data do not identify a unique link.': '损失差 < 10⁻⁸。并列时按固定规则选择恒等尺度；数据未识别出唯一的链接函数。',
  'Both losses use the same grid, quadrature and positive-amplitude profiling.': '两种损失使用相同网格、数值积分和正幅度剖面拟合。',
  'The scale buttons change the view. Future selection always uses the historical losses above.': '尺度按钮只改变视图。未来决策始终依据上面的历史损失进行选择。',
  'Advanced: reference action': '高级：参考动作',
  'Reference action': '参考动作',
  'Analytic reference inside [0,1]. Changing it leaves the original responses, logging and pooled target intact.': '参考动作位于 [0,1]，其响应由解析式计算。调整它不会改变原始响应、记录策略或混合目标。',
  'Change only the future shape': '只调整未来形状',
  'Change future calibration': '调整未来校准',
  'Persistent future': '形状延续的未来',
  'Shape-changing future': '形状改变的未来',
  'Future shape shock': '未来形状冲击',
  'ε affects future truth only. The historical rule stays frozen.': 'ε 只影响未来真值。历史决策规则保持冻结。',
  'Future level': '未来响应水平',
  'Offset in the generating log-response scale': '生成模型的对数响应尺度偏移',
  'Offset in the raw response scale': '原始响应尺度偏移',
  'Future amplitude': '未来幅度',
  'Positive amplitude in the generating response family': '生成响应族中的正幅度',
  'Future revealed': '未来已揭示',
  'Reveal future': '揭示未来',
  'Changing future parameters hides the truth again. It never refits the historical rule.': '调整未来参数会再次隐藏真值，历史决策规则不会重新拟合。',
  'Frozen from history': '由历史冻结',
  'Selected scale': '所选尺度',
  ' (tie preference)': '（并列时的固定选择）',
  'Both scales fit the history. This does not identify which geometry will persist into a new calibration.': '两种尺度均能拟合历史。这并未识别哪种几何结构会在新的校准下延续。',
  'Frozen geometry action': '冻结的几何动作',
  'Historical pooled action': '历史混合动作',
  'Future truth, oracle and regret are hidden.': '未来真值、最优动作及遗憾值均已隐藏。',
  'A future branch requires an identified historical geometry': '未来分支需要由历史识别出的动作几何。',
  'A future branch must freeze its matching historical anchor and selected link': '未来分支必须冻结与该历史对应的参考动作和所选链接函数。',
  'The future calibration exceeds finite numerical response values.': '未来校准产生了超出有限数值范围的响应。',
  'The frozen log scale requires positive future responses across support.': '冻结的对数尺度要求整个支撑域内的未来响应均为正。',
  'No numerically resolved future action signal for this calibration.': '当前校准下无法在数值精度内分辨未来动作信号。',
  'Simulated truth diagnostic': '模拟真值诊断',
  'Revealed oracle action': '揭示后的真值最优动作',
  'Frozen geometry raw regret': '冻结几何动作的原始遗憾',
  'Pooled action, future raw regret': '混合动作的未来原始遗憾',
  'Relative linked mismatch': '尺度变换后的相对失配',
  'Raw regrets are in outcome units. Relative mismatch is ‖residual‖w / ‖linked contrast‖w in the selected historical scale.': '原始遗憾以结果单位计量。相对失配为所选历史尺度下的 ‖residual‖w / ‖linked contrast‖w。',
  'Show structural bound': '显示结构性界限',
  'Geometry linked regret': '几何动作的变换尺度遗憾',
  '2 ‖true residual‖∞': '2 ‖真实残差‖∞',
  'The nonnegative future amplitude is profiled against the frozen shape, on the same grid and selected link. The displayed linked regret is bounded by twice the sup residual.': '在相同网格和所选链接函数下，针对冻结形状拟合未来的非负幅度。所展示的变换尺度遗憾不超过残差上确界的两倍。',
  'Known future truth audit.': '已知未来真值审计。',
  'This is not an observable deployment confidence interval, a safety certificate, or a statistical estimator guarantee.': '这不是部署中可观测的置信区间、安全认证或统计估计器保证。',
  'Identity is selected: linked and raw regret have the same units and value.': '当前选择恒等尺度：变换尺度遗憾与原始遗憾的单位及数值相同。',
  'Log is selected: linked regret is in log-response units, while raw regret is in outcome units.': '当前选择对数尺度：变换尺度遗憾使用对数响应单位，原始遗憾使用结果单位。',
  'No positive future scale fits this direction. The 3D truth overlay is omitted; raw truth and residual diagnostics remain available.': '没有正的未来尺度能拟合该方向。3D 真值叠加曲线已省略，原始真值和残差诊断仍可查看。',
  'A scale acts on the response curve': '尺度变换作用于响应曲线',
  'An anchor removes response level': '参考动作消去响应水平',
  'Positive amplitude leaves the shape': '移除正幅度，保留形状',
  'The link transforms the known conditional mean mₜ(a). Sample points are hidden; taking logs of noisy outcomes would be a different operation.': '链接函数变换的是已知条件均值 mₜ(a)。样本点已隐藏；对带噪结果取对数是另一种操作。',
  'Each contrast subtracts the analytic response at the same reference action a₀. The gray reference is distinct from the preferred action.': '每条对比曲线均减去同一参考动作 a₀ 处的解析响应。灰色参考线与偏好动作不同。',
  'Divide each linked contrast by its positively profiled amplitude. The shared curve has weighted norm one. Curves only coincide when that scale actually fits.': '将每条尺度变换后的对比曲线除以拟合出的正幅度。共享曲线的加权范数为 1。只有该尺度确实拟合时，曲线才会重合。',
  'Viewing': '当前视图：',
  'identity': '恒等',
  'log': '对数',
  'computed preferred action': '计算所得偏好动作',
  '. A lower geometry loss need not produce a different action in this monotone teaching family.': '。在这个单调变换教学族中，较低的几何损失不一定产生不同的动作。',
  'The fitting rule in this illustration': '本演示的拟合规则',
  'sₜ = max(0, ⟨Δₜ, ρ⟩w / ⟨ρ, ρ⟩w). Loss is the period-averaged squared residual divided by each contrast’s energy, using common trapezoidal weights.': 'sₜ = max(0, ⟨Δₜ, ρ⟩w / ⟨ρ, ρ⟩w)。损失为各时期残差平方除以各自对比曲线能量后的平均值，使用相同的梯形积分权重。',
  'The known-curve, fixed-context fit uses aligned power iteration. It does not claim to solve the paper’s general representation or shape-library optimization.': '这个固定情境下的已知曲线拟合使用对齐的幂迭代，并不声称求解论文的一般表示或形状库优化问题。',
  'How this connects to the estimator': '这与论文估计器有何联系',
  'The paper’s two-stage orthogonal estimation workflow separates nuisance learning from held-out geometry selection. This teaching fit implements neither statistical stage.': '论文的两阶段正交估计流程将干扰函数学习与留出数据上的几何选择分开。本教学拟合未实现任何一个统计阶段。',
  'Observational histories.': '观测历史。',
  'Identification needs histories, exchangeability and support; time mixing is isolated in this toy model.': '识别需要历史、可交换性和支撑条件；这个教学模型单独展示跨时间混合问题。',
  'Stage 1: cross-fitted response pilots.': '阶段 1：交叉拟合的响应初估。',
  'The paper workflow estimates conditional responses. This browser starts from known curves instead.': '论文流程估计条件响应。本网页从已知曲线出发。',
  'Stage 2: held-out orthogonal profiled selection.': '阶段 2：留出数据上的正交剖面选择。',
  'Candidate scales and geometry are assessed through profiled criteria. Here, the population curves supply the teaching comparison.': '通过剖面准则评估候选尺度和几何结构。本演示的比较由总体响应曲线提供。',
  'Decision rule.': '决策规则。',
  'The selected geometry defines an action before future outcomes are observed.': '在观察未来结果之前，所选几何结构已确定动作。',
  'Structural illustrations, criterion-level statistical guarantees and conditional policy guarantees are separate claims. The future truth bound above illustrates a structural inequality; it does not implement or validate the full statistical estimator.': '结构演示、准则层面的统计保证和条件策略保证是不同的主张。上面的未来真值界限展示的是结构性不等式，并未实现或验证完整统计估计器。',
  'What is the red curve computing?': '红色曲线计算了什么？',
  'The population conditional mean, using seven equally weighted periods:': '使用七个等权时期计算总体条件均值：',
  'is the known response and': '是已知响应，',
  'is the normalized logging density. The conditional weights depend on action. This is an ideal predictor, with no finite-sample fitting error.': '是归一化的记录密度。条件权重依赖于动作。这是理想预测器，不包含有限样本拟合误差。',
  'Ideal pooled action': '理想混合动作',
  'True preferred action': '真实偏好动作',
  'The two optima coincide.': '两个最优动作重合。',
  'Prediction and decision point to different actions.': '预测与决策指向不同动作。',
};
