/** Exact English source keys keep visual translations separate from model state. */
export const visualZh: Record<string, string> = {
  'Action': '动作',
  'Action a': '动作 a',
  'Response': '响应',
  'response': '响应',
  'Period': '时期',
  'period': '时期',
  'Early': '早期',
  'Middle': '中期',
  'Late': '后期',
  'Future': '未来',
  'Reference': '参考动作',
  'identity': '恒等',
  'log': '对数',
  'Log response': '对数响应',
  'Identity linked contrast': '恒等尺度响应差',
  'Log linked contrast': '对数尺度响应差',
  'Normalized linked contrast': '归一化尺度响应差',
  'Scaled linked contrast': '缩放后的尺度响应差',
  'log response': '对数响应',
  'identity linked contrast': '恒等尺度响应差',
  'log linked contrast': '对数尺度响应差',
  'normalized linked contrast': '归一化尺度响应差',
  'scaled linked contrast': '缩放后的尺度响应差',
  'Known true optimum': '已知真值最优动作',
  'Same action': '相同动作',
  'Pooled optimum': '混合目标最优动作',
  'Geometry action': '形状决定的动作',
  'Revealed oracle': '揭示后的真值最优动作',
  'Observed': '历史观测',
  'Assumed continuation': '假设的延续',
  'Revealed truth': '揭示的真值',
  'Vertical axis': '纵轴',
  '3D is unavailable here. Explore the synchronized response plot below.': '此设备无法显示 3D。请探索下方同步的响应图。',
  '3D scene of known curves on the': '已知响应曲线的三维场景，使用',
  'scale': '尺度',
  '3D scene of known response curves across seven historical periods': '七个历史时期的已知响应曲线三维场景',
  'Action runs horizontally, response vertically, and period into depth. Synchronized plots and controls provide the same data below.': '横轴表示动作，纵轴表示响应，深度轴表示时期。下方同步图表与控件提供相同数据。',
  'Known synthetic response curves across seven historical periods. Explore the synchronized response plot below.': '七个历史时期的已知合成响应曲线。请探索下方同步的响应图。',
  'Scaled linked contrast · continuation assumes persistent shape': '缩放后的尺度响应差 · 延续假设形状保持稳定',
  'Positive amplitude removed · time depth collapsed': '已移除正幅度 · 时间深度已折叠',
  'Gray reference action and zero plane · no data regeneration': '灰色参考动作与零平面 · 原始数据不变',
  'Known response curves on the selected link scale': '所选链接尺度上的已知响应曲线',
  'Floor strips: time-dependent logging density': '底部条带：随时间变化的日志动作密度',
  'One period, in focus': '聚焦一个时期',
  'Same response axis across periods': '各时期共用同一响应轴',
  'Known period': '已知时期',
  ' and ideal pooled response': '与理想混合响应',
  '; click to move the action cursor': '；点击可移动动作游标',
  'Known period response': '已知时期响应',
  'Ideal pooled predictor': '理想混合预测器',
  'True optimum (synthetic truth)': '真值最优动作（合成真值）',
  'Action cursor': '动作游标',
  'Use the Action cursor slider to explore the same values with a keyboard.': '可使用动作游标滑块，通过键盘探索相同数值。',
  'Which times make this prediction?': '这一预测混合了哪些时期？',
  'Conditional period proportions at action': '给定动作下各时期的条件比例，动作',
  '0 · low action': '0 · 小动作',
  'high action · 1': '大动作 · 1',
  'Move the cursor. The mix of periods changes with the action.': '移动游标。混合的时期比例随动作变化。',
  'A shared geometry, in focus': '聚焦共同响应形状',
  'Seven curves, one scale': '七条曲线，共用一个尺度',
  'for seven known periods on the': '：七个已知时期，使用',
  'scale. Click to move the action cursor.': '尺度。点击可移动动作游标。',
  'Known period curves': '已知时期曲线',
  'Reference action a₀': '参考动作 a₀',
  'Fitted geometry ρ': '拟合的响应形状 ρ',
  'Illustrative geometry fit on known response curves.': '对已知响应曲线进行教学用形状拟合。',
  'All seven periods share this display scale; depth is collapsed in 3D.': '七个时期共用此显示尺度；3D 中的时间深度已折叠。',
  'The action cursor is shared with the 3D scene.': '动作游标与 3D 场景同步。',
  'Frozen geometry ρ · dimensionless': '冻结的响应形状 ρ · 无量纲',
  'Revealed future truth · raw response': '揭示的未来真值 · 原始响应',
  'A frozen choice, a revealed future': '冻结的决策，揭示的未来',
  'Choose with geometry only': '只依据响应形状决策',
  'Aligned actions · separate units': '动作轴对齐 · 量纲分别显示',
  'Frozen dimensionless geometry and revealed raw future truth on separate aligned axes. Simulated truth diagnostic.': '冻结的无量纲响应形状与揭示的未来原始真值显示在分别对齐的坐标轴上。这是模拟真值诊断。',
  'Assumed dimensionless geometry continuation. Future outcomes are hidden.': '假设无量纲响应形状延续。未来结果保持隐藏。',
  'Frozen CAG action': '冻结的 CAG 动作',
  'Revealed truth / oracle': '揭示的真值 / 最优动作',
  'Frozen pooled action': '冻结的混合目标动作',
  'Simulated truth diagnostic. Raw future outcomes appear on their own axis; dimensionless geometry does not predict an outcome level.': '模拟真值诊断。未来原始结果显示在单独的响应轴上；无量纲响应形状不预测结果水平。',
  'Future outcomes are hidden. The dashed continuation assumes persistent shape, with no predicted outcome level.': '未来结果保持隐藏。虚线延续假设响应形状稳定，不预测结果水平。',
  'The future calibration exceeds finite numerical response values.': '未来校准超出有限响应数值范围。',
  'The frozen log scale requires positive future responses across support.': '冻结的对数尺度要求整个动作范围内的未来响应均为正。',
  'No numerically resolved future action signal for this calibration.': '此校准下没有数值上可分辨的未来动作信号。',
}
